/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javatuples2;

import org.javatuples.Ennead;
import org.javatuples.Pair;

public class App {
    public static void main(String[] args) {
       Pair<Integer, String> myPair = new Pair<Integer,String>(3, "Hi");  
       Ennead<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> myennead = new Ennead<A,B,C,D,E,F,G,H,I>(
        3, 
        3, 
        3, 
        3, 
        3, 
        3, 
        3, 
        3);
    }
}
